config/routes.rb
Rails.application.routes.draw do
  resources :searches, only: [:new, :create]
  resources :albums, only: :show
  root 'searches#new'
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = RSpotify::Album.find(params[:id])
    @tracks = @album.tracks
    @artists = @album.artists
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
  end

  def create
    query   = params[:search][:query] if params[:search]
    types   = 'artist, album, track'
    results = RSpotify::Base.search(query, types)

    @artists  = prepare_results(results, RSpotify::Artist)
    @albums   = prepare_results(results, RSpotify::Album)
    @tracks   = prepare_results(results, RSpotify::Track)

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  private
  def prepare_results(results, type)
    results.select { |r| r.class == type }.sort { |x, y| y.popularity <=> x.popularity }
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def format_duration(ms)
    ss = ms / 1000
    mm, ss = ss.divmod(60)
    hh, mm = mm.divmod(60)
    __, hh = hh.divmod(24)
    results = ""
    results += "#{left_pad(hh)}:" if hh > 0
    results += "#{left_pad(mm)}:" if mm > 0
    results += "#{left_pad(ss)}" if ss > 0
  end

  def popularity_stars(popularity)
    full_stars, half_star, empty_stars = get_number_of_stars(popularity)
    results = full_stars.times.map { fa_icon('star') }
    results << fa_icon('star-half-full') if half_star
    results << empty_stars.times.map { fa_icon('star-o') }
    results.join('').html_safe
  end

  def play_button(uri)
    link_to '#', class: 'pure-button search-command search-command-play' do
      fa_icon 'play', text: 'Play'
    end
  end

  def queue_button(uri)
    link_to '#', class: 'pure-button search-command search-command-queue' do
      fa_icon 'plus', text: 'Queue'
    end
  end

  private
  def get_number_of_stars(popularity)
    full_stars, remainder = popularity.divmod(20)
    half_star = true if remainder >= 10
    total_stars = 5
    empty_stars = total_stars - full_stars
    empty_stars -= 1 if half_star
    [full_stars, half_star, empty_stars]
  end

  def left_pad(number)
    number.to_s.rjust(2, "0")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper

  def artist_image(images, name)
    if images.count >= 1
      image_tag images[1]['url'], alt: name, height: 300, width: 300, class: 'results-img'
    else
      fa_stacked_icon 'question', base: 'square-o', class: 'results-no-artist'
    end
  end
end

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<%= image_tag(@album.images[1]['url'], alt: @album.name) %>
<p>Artist Name: <%= @artists.first.name %></p>
<p>Popularity: <%= popularity_stars(@album.popularity) %></p>
<%= render 'common/tracks' %>

app/views/common/_tracks.html.erb
<h1 class="center results-header">Tracks</h1>
<table class="pure-table pure-table-horizontal pure-table-striped results-tracks">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Duration</th>
      <th>Popularity</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @tracks.each.with_index(1) do |track, index| %>
    <tr>
      <td><%= index %></td>
      <td><%= track.name %></td>
      <td><%= track.artists.first.name %></td>
      <td><%= track.album.name %></td>
      <td><%= format_duration(track.duration_ms) %></td>
      <td><%= popularity_stars(track.popularity) %></td>
      <td>
        <%= play_button(track) %>
        <%= queue_button(track) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
  <a href="<%= root_url %>" class="pure-menu-heading">
    <%= fa_icon 'headphones' %>
    DudePlayMe
  </a>
    <li><%= link_to 'Search', new_search_path %></li>
    <li><a href="#">Player</a></li>
    <li><a href="#">Status</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>DudePlayMe</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= google_webfonts_link_tag raleway: [400, 700] %>
<%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/searches/_albums.html.erb
<h1 class="center results-header">Albums</h1>
<div class="albums pure-g">
  <% @albums.each_slice(3) do |row| %>
    <% row.each do |album| %>
      <div class="pure-u-1-3">
        <%= link_to(image_tag(album.images[1]['url'], alt: album.name, height: 300, width: 300, class: 'results-img'), album_path(album.id)) %>
        <p>
        <%= fa_icon 'music', class: 'results-icon' %>
        <%= link_to album.name, album_path(album.id), class: 'pure-button results-info' %></p>
        <p>
        <%= fa_icon 'user', class: 'results-icon' %>
        <%= album.artists.map { |a| link_to(a.name, '#', class: 'pure-button results-info') }.join(', ').html_safe %>
        </p>
        <p class="results-icon"><%= popularity_stars(album.popularity) %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/searches/_artists.html.erb
<h1 class="center results-header">Artists</h1>
<div class="artists pure-g">
  <% @artists.each_slice(3) do |row| %>
    <% row.each do |artist| %>
      <div class="pure-u-1-3">
        <%= link_to(artist_image(artist.images, artist.name), '#') %>
        <p>
        <%= fa_icon 'user', class: 'results-icon' %>
        <%= link_to artist.name, '#', class: 'pure-button results-info' %>
        </p>
        <p class="results-icon"><%= popularity_stars(artist.popularity) %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/searches/create.html.erb
<div class="pure-g results">
  <div class="pure-u-1">
    <%= render 'common/tracks' %>
  </div>
  <div class="pure-u-1">
    <%= render 'albums' %>
  </div>
  <div class="pure-u-1">
    <%= render 'artists' %>
  </div>
</div>

app/views/searches/new.html.erb
<div class="music-search-container">
  <div class="music-search">
    <div class="search-logo-area">
      <%= fa_icon 'headphones' %>
    </div>
    <%= form_tag(searches_path, id: 'search', class: 'pure-form') do %>
      <div class="search-input-area">
        <%= search_field(:search, :query, placeholder: 'Find Music', class: 'search-input pure-u-1', autofocus: true) %>
      </div>
      <div class="search-button-area">
        <%= button_tag(type: :submit, class: 'pure-button pure-button-primary search-button') do |button| %>
          <%= fa_icon 'search' %> Search
        <% end %>
      </div>
    <% end %>
    <div class="search-results-area"></div>
  </div>
</div>